"""
main.py
--------
Entry point for the LibQuery FastAPI backend.

Run this with (from inside the 'app' folder):
    uvicorn main:app --reload

Endpoints:
    GET  /        -> confirms the API is running
    POST /query   -> takes a natural-language question and returns SQL,
                      an explanation, and (if safe) the query results
"""

from fastapi import FastAPI, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy.orm import Session

from database import get_db, run_select_query, check_database_connection
from ollama_client import ask_llama, OllamaConnectionError, OllamaModelError
from sql_validator import validate_sql

# ---------------------------------------------------------------------------
# APP SETUP
# ---------------------------------------------------------------------------
app = FastAPI(
    title="LibQuery API",
    description="Natural-language to SQL query system for a library database.",
    version="1.0.0",
)

# Allow the frontend (served from a different port, e.g. 5500) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # for a college project, allowing all origins is fine
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# REQUEST / RESPONSE MODELS
# ---------------------------------------------------------------------------
class QuestionRequest(BaseModel):
    """Shape of the incoming request body for POST /query"""
    question: str


class QueryResponse(BaseModel):
    """Shape of the response returned by POST /query"""
    question: str
    sql: str = ""
    explanation: str = ""
    success: bool
    data: list = []
    error: str = ""


# ---------------------------------------------------------------------------
# ROUTES
# ---------------------------------------------------------------------------
@app.get("/")
def read_root():
    """Simple health-check route to confirm the API is working."""
    return {"message": "LibQuery FastAPI backend is running successfully."}


@app.post("/query", response_model=QueryResponse)
def process_query(request: QuestionRequest, db: Session = Depends(get_db)):
    """
    Main endpoint: takes a natural-language question, asks Llama 3.2 to
    convert it into SQL, validates the SQL, runs it against MySQL, and
    returns everything (or a clear error message if something fails).
    """
    question = (request.question or "").strip()

    # ---- 1. Handle empty questions -----------------------------------
    if not question:
        return QueryResponse(
            question=question,
            success=False,
            error="Please enter a question before generating a query.",
        )

    # ---- 2. Ask Ollama / Llama 3.2 to generate SQL --------------------
    try:
        ai_result = ask_llama(question)
    except OllamaConnectionError as e:
        # Covers: Ollama not running
        return QueryResponse(question=question, success=False, error=str(e))
    except OllamaModelError as e:
        # Covers: Llama 3.2 model not installed
        return QueryResponse(question=question, success=False, error=str(e))
    except ValueError as e:
        # Covers: questions that cannot be converted into SQL / bad AI output
        return QueryResponse(
            question=question,
            success=False,
            error=f"Could not understand the question well enough to build a query. ({e})",
        )
    except Exception as e:
        # Catch-all so the API never crashes on an unexpected error
        return QueryResponse(
            question=question,
            success=False,
            error=f"Unexpected error while contacting the AI model: {e}",
        )

    sql = ai_result["sql"]
    explanation = ai_result["explanation"]

    # ---- 3. Validate the generated SQL for safety ----------------------
    is_valid, validation_message = validate_sql(sql)
    if not is_valid:
        # Covers: invalid / unsafe SQL generated by AI
        return QueryResponse(
            question=question,
            sql=sql,
            explanation=explanation,
            success=False,
            error=f"Generated SQL was rejected for safety reasons: {validation_message}",
        )

    # ---- 4. Check the database connection first ------------------------
    connected, connection_error = check_database_connection()
    if not connected:
        # Covers: MySQL connection errors
        return QueryResponse(
            question=question,
            sql=sql,
            explanation=explanation,
            success=False,
            error=f"Could not connect to the MySQL database: {connection_error}",
        )

    # ---- 5. Execute the validated SELECT query -------------------------
    exec_success, result_or_error = run_select_query(db, sql)
    if not exec_success:
        # Covers: SQL execution errors, unknown tables/columns
        return QueryResponse(
            question=question,
            sql=sql,
            explanation=explanation,
            success=False,
            error=result_or_error,
        )

    # ---- 6. Success! Return everything ----------------------------------
    return QueryResponse(
        question=question,
        sql=sql,
        explanation=explanation,
        success=True,
        data=result_or_error,
        error="",
    )